# Generated by Django 2.2 on 2019-10-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='image_path/')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
