# Generated by Django 2.2 on 2019-10-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='item', max_length=10),
            preserve_default=False,
        ),
    ]
