# Generated by Django 2.2.7 on 2019-12-02 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('can_read_private', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_remove', models.BooleanField(default=False)),
                ('can_update_contributors', models.BooleanField(default=False)),
                ('can_remove_contributors', models.BooleanField(default=False)),
                ('fk_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.FileModel')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
