# Generated by Django 2.2.7 on 2019-12-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='delete_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
