# Generated by Django 2.2.7 on 2019-12-03 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filemodel_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
    ]
